### ISSUE TITLE
Allow clouds to render past the games render distance

### ISSUE THREAD

**Issue by RJWadley** [Soulphur0/ElytraAeronautics#6]
I think it'd be nice if the clouds could render past the games render distance into the horizon.

[Extended Clouds](https://www.curseforge.com/minecraft/mc-mods/extended-clouds) does this, but it's not compatible with Elytra Aeronautics.

**Comment by Soulphur0** [comment]
I'll look into it, with the recent release of [my new mod](https://github.com/Soulphur0/Comet), I might have some time to check that out, and fix a couple of bugs along the way.

**Comment by Soulphur0** [comment]
With the latest Elytra Aeronautics release (1.2.0) you can now specify cloud render distance and it is independent from chunk render distance. In fact you can crank it up as far as you want! (If your pc can handle it of course)

Also, due to some compatibility fixes, the mod now works with extended clouds, if you want to use its specific rendering, just set the 'useEanCloudRender' setting to 'false'.
