### ISSUE TITLE
Serverside-only compatibility? 

### ISSUE THREAD

**Issue by piebaker** [Soulphur0/ElytraAeronautics#9]
Just came across this mod, truely an awesome idea. 
Is it possible to load this only serverside with the higher=faster feature, while loading clientside provides the cloud functionality?

**Comment by Soulphur0** [comment]
Hello! Thank you for trying out the mod.

I'm not quite sure about the meaning of your question, the higher=faster behavior already works only server-side, and the cloud functionality only works client-side.

This means that flight settings will always affect all of the players on the server while cloud settings are independent from each player; although you can still play in singleplayer and flight settings will be your own because all worlds run on an internal server.

For the mod to work on a dedicated server it will need to be installed on it.

**Comment by piebaker** [comment]
Oh excellent! 
I hadn't yet installed it on our dedicated server, i just read the modrinth page requiring it on the client side and posted this question. I'll be installing this now that i know it's not strictly required clientside, cheers!
